services:
    todo_rest_api:
        container_name: todo_rest_api
        image: lucassantos06/todo-rest-api:${DOCKER_IMAGE_TAG}
        env_file: .env
        ports:
            - "8000:8000"
        depends_on:
            - todo_postgresql
        networks:
            - todo_network

    todo_postgresql:
        container_name: todo_postgresql
        image: lucassantos06/todo-postgresql:${DOCKER_IMAGE_TAG}
        volumes:
            - todo_data:/var/lib/postgresql/data
        restart: always
        env_file: .env
        ports:
            - "5433:5432"
        networks:
            - todo_network

    todo_postgresql_exporter:
        container_name: todo_postgresql_exporter
        image: prometheuscommunity/postgres-exporter:latest
        platform: linux/arm64
        environment:
            DATA_SOURCE_NAME: ${DATA_SOURCE_NAME}
        ports:
            - "9187:9187"
        depends_on:
            - todo_postgresql
        networks:
            - todo_network

    todo_prometheus:
        container_name: todo_prometheus
        image: lucassantos06/todo-prometheus:${DOCKER_IMAGE_TAG}
        ports:
            - "9090:9090"
        depends_on:
            - todo_rest_api
            - todo_postgresql_exporter
        networks:
            - todo_network

    todo_grafana:
        container_name: todo_grafana
        image: lucassantos06/todo-grafana:${DOCKER_IMAGE_TAG}
        env_file: .env
        ports:
            - "3000:3000"
        depends_on:
            - todo_prometheus
        networks:
            - todo_network

volumes:
    todo_data:

networks:
    todo_network:
        driver: bridge
