FROM golang:1.23 AS builder

COPY src /app/src
COPY .env /app/.env
COPY docs /app/docs
COPY go.mod /app
COPY go.sum /app
COPY main.go /app

WORKDIR /app

RUN go mod tidy && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o todo-rest-api


FROM gcr.io/distroless/static

COPY --from=builder /app/.env /.env
COPY --from=builder /app/todo-rest-api /todo-rest-api

ENTRYPOINT ["/todo-rest-api"]
