FROM grafana/grafana:latest

COPY grafana/provisioning/datasources/datasources.yml /etc/grafana/provisioning/datasources/datasources.yml
COPY grafana/provisioning/dashboards/dashboards.yml /etc/grafana/provisioning/dashboards/dashboards.yml

COPY grafana/dashboards /var/lib/grafana/dashboards
