\connect todo_db;

CREATE USER $POSTGRES_SERVICE_USER WITH PASSWORD '$POSTGRES_SERVICE_USER_PASSWORD';
GRANT CONNECT ON DATABASE $POSTGRES_DB TO $POSTGRES_SERVICE_USER;
GRANT USAGE ON SCHEMA public TO $POSTGRES_SERVICE_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $POSTGRES_SERVICE_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO $POSTGRES_SERVICE_USER;

