services:
    todo_postgresql_dev:
        container_name: todo_postgresql_dev
        build:
            context: ../
            dockerfile: docker/Dockerfile
            args:
                POSTGRES_DB: todo_db
                POSTGRES_SERVICE_USER: todo_service
                POSTGRES_SERVICE_USER_PASSWORD: todo_service_password
#        volumes: # Uncomment these lines if you want to persist the data even after deleting the container
#            - todo_data:/var/lib/postgresql/data # Uncomment these lines if you want to persist the data even after deleting the container
        restart: always
        environment:
            POSTGRES_DB: todo_db
            POSTGRES_USER: todo_user
            POSTGRES_PASSWORD: todo_password
        ports:
            - "5434:5432"

#volumes: # Uncomment these lines if you want to persist the data even after deleting the container
#    todo_data: # Uncomment these lines if you want to persist the data even after deleting the container
