version: '3'

services:
  db:
    container_name: todo-database-dev
    build:
      dockerfile: ./docker/Dockerfile
      context: "../"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    ports:
      - "5432:5432"
    networks:
      - todo

networks:
  todo:
    driver: bridge